# Generated by Django 5.0.1 on 2024-01-07 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded_image/'),
        ),
    ]
